// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AiAssistantController from "./ai_assistant_controller"
application.register("ai-assistant", AiAssistantController)

import AiProfileGeneratorController from "./ai_profile_generator_controller"
application.register("ai-profile-generator", AiProfileGeneratorController)

import BrandingPreviewController from "./branding_preview_controller"
application.register("branding-preview", BrandingPreviewController)

import CommentableController from "./commentable_controller"
application.register("commentable", CommentableController)

import ConditionFormController from "./condition_form_controller"
application.register("condition-form", ConditionFormController)

import ConfettiController from "./confetti_controller"
application.register("confetti", ConfettiController)

import DashboardChartController from "./dashboard_chart_controller"
application.register("dashboard-chart", DashboardChartController)

import DocumentPreviewController from "./document_preview_controller"
application.register("document-preview", DocumentPreviewController)

import DrawerController from "./drawer_controller"
application.register("drawer", DrawerController)

import DrawerTriggerController from "./drawer_trigger_controller"
application.register("drawer-trigger", DrawerTriggerController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ExpandableCellController from "./expandable_cell_controller"
application.register("expandable-cell", ExpandableCellController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import KanbanController from "./kanban_controller"
application.register("kanban", KanbanController)

import LoaderController from "./loader_controller"
application.register("loader", LoaderController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PermissionFormController from "./permission_form_controller"
application.register("permission-form", PermissionFormController)

import RegulatoryAutoConfigController from "./regulatory_auto_config_controller"
application.register("regulatory-auto-config", RegulatoryAutoConfigController)

import SourceTypeToggleController from "./source_type_toggle_controller"
application.register("source-type-toggle", SourceTypeToggleController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TagifyController from "./tagify_controller"
application.register("tagify", TagifyController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import WorkflowEditorController from "./workflow_editor_controller"
application.register("workflow-editor", WorkflowEditorController)
